### ISSUE TITLE
Regexp based naming in config

### ISSUE THREAD

**Issue by paalvibe** [brickops/brickops#37]
Enable a regexp pattern to support any kind of path. It could be something like this:

```
naming:
  regexp: "domains/([^/]+)/projects/([^/]+)/flows/([^/]+)/([^/]+)"
  segments: "domain,project,flowtype,flow"
  job:
    prod: "{domain}_{project}_{env}"
    other: "{domain}_{project}_{env}_{username}_{gitbranch}_{gitshortref}"
  pipeline:
    prod: "{domain}_{project}_{env}_dlt"
    other: "{domain}_{project}_{env}_{username}_{gitbranch}_{gitshortref}_dlt"
  catalog:
    prod: "{domain}"
    other: "{domain}"
  db:
    prod: "{db}"
    other: "{env}_{username}_{gitbranch}_{gitshortref}_{db}"
```
